create table reservation (
        end_date date not null,
        initial_date date not null,
        id bigint generated by default as identity,
        user_id bigint,
        reservation_status varchar(255) check (reservation_status in ('ACTIVE','CANCELED','NOT_RESERVED')),
        primary key (id)
);