create table room (
        capacity integer not null,
        id bigint generated by default as identity,
        name varchar(255) not null,
        room_status varchar(255) check (room_status in ('ACTIVE','INACTIVE')),
        primary key (id)
);