create table users (
        age integer not null,
        id bigint generated by default as identity,
        cpf varchar(255) not null unique,
        email varchar(255) not null unique,
        name varchar(255) not null,
        phone varchar(255) not null unique,
        primary key (id)
);